services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: yuta
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    depends_on:
      - db
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
  next:
    build:
      context: ./next
    tty: true
    stdin_open: true
    command: "npm run dev"
    ports:
      - 8000:3000
    volumes:
      - ./next:/myapp
volumes:
  mysql_data:
    
