services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: yuta
      POSTGRES_PASSWORD: uta12242002
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5433:5432"
  rails:
    build:
      context: ./rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  next:
    build:
      context: ./next
    tty: true
    stdin_open: true
    command: "npm run dev"
    ports:
      - "8000:3000"
    volumes:
      - ./next:/myapp
volumes:
  postgres-data:
    
