default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: yuta
  port: 3306

development:
  <<: *default
  host: db
  database: myapp_development
  password: password

test:
  <<: *default
  host: db
  username: root
  database: myapp_test
  password: password

production:
   <<: *default
   database: myapp_production
   url: <%= Rails.application.credentials.production.database_url %>